services:  
  mysql:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_DATABASE: nullpointer
      MYSQL_USER: myuser
      MYSQL_PASSWORD: 123123
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ~/dev/mysql-data:/var/lib/mysql
    networks:
      - nullpointer

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "5000:8080"
    depends_on:
      - mysql
    networks:
      - nullpointer
  
  api-nullpointer:
    build: 
      context: ./src/api
      args:
        - WEBAPP_BASE_URL=http://localhost:9000
    image: dalmofelipe/nullpointer-api:0.1.0
    container_name: nullpointer-api
    environment:
      - WEBAPP_BASE_URL=http://localhost:9000
      - DB_HOST=mysql
    depends_on:
      - mysql
    ports:
      - "8000:8000"
    networks:
      - nullpointer

  webapp-nullpointer:
    build: 
      context: ./src/web
      args:
        - API_BASE_URL=http://localhost:8000/api
    image: dalmofelipe/nullpointer-webapp:0.1.0
    container_name: nullpointer-webapp
    ports:
      - "9000:80"
    networks:
      - nullpointer

networks:
  nullpointer:

volumes:
  mysql-data:
