
###
GET http://localhost:8000/api/perguntas HTTP/1.1


###
GET http://localhost:8000/api/perguntas/1 HTTP/1.1


###
POST http://localhost:8000/api/perguntas HTTP/1.1
Content-Type: application/json

{
    "titulo": "Docker compose não inicializa database MySQL",
    "mensagem": "Mussum Ipsum, cacilds vidis litro abertis. ### Titulo 3 Negão é teu passadis, eu sou faxa pretis. Delegadis gente finis, bibendum egestas augue arcu ut est. Tá deprimidis, eu conheço uma cachacis que pode alegrar sua vidis. Atirei o pau no gatis, per gatis num morreus.",
    "tags": ["docker", "docker-compose", "spring-boot", "java", "web", "development", "backend"]
}


################### RESPOSTAS #########################
###
POST http://localhost:8000/api/respostas HTTP/1.1
Content-Type: application/json

{
    "pergunta_id": 1,
    "mensagem": "compose so funciona na primeira execução do compose up. tera que excluir os arquivos do volume montado!"
}


################### COMENTANDO RESPOSTAS #########################
###
POST http://localhost:8000/api/comentarios HTTP/1.1
Content-Type: application/json

{
    "resposta_id": 1,
    "mensagem": "funfo!"
}