
###
GET http://localhost:8000/api/perguntas HTTP/1.1


###
GET http://localhost:8000/api/perguntas/1 HTTP/1.1


###
POST http://localhost:8000/api/perguntas HTTP/1.1
Content-Type: application/json

{
    "titulo": "Docker compose não inicializa database MySQL",
    "mensagem": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec luctus ante et congue ornare. Phasellus auctor lobortis ligula id euismod. Cras consectetur nisi sit amet odio finibus, vitae tincidunt libero maximus!",
    "tags": "docker,docker-compose,spring-boot,java,web,development,backend"
}


################### RESPOSTAS #########################
###
POST http://localhost:8000/api/respostas HTTP/1.1
Content-Type: application/json

{
    "pergunta_id": 1,
    "mensagem": "As configurações do mysql via env vars são aplicadas na somente na primeira execução do docker compose up, Exclua os arquivos do volume montado e rode o compose up novamente!"
}


################### COMENTANDO RESPOSTAS #########################
###
POST http://localhost:8000/api/comentarios HTTP/1.1
Content-Type: application/json

{
    "resposta_id": 1,
    "mensagem": "Funfo! VLWWW"
}

###
POST http://localhost:8000/api/comentarios HTTP/1.1
Content-Type: application/json

{
    "resposta_id": 1,
    "mensagem": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec luctus ante et congue ornare. Phasellus auctor lobortis ligula id euismod. Cras consectetur nisi sit amet odio finibus, vitae tincidunt libero maximus.!"
}