server:
  port: 8000
  error:
    include-stacktrace: never

spring:
  application:
    name: ApiNullPointer
  datasource:
    url: jdbc:mysql://localhost:3306/nullpointer
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
    open-in-view: false
