server:
  port: 8000
  error:
    include-stacktrace: never

spring:
  application:
    name: ApiNullPointer
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost:3306}/nullpointer
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER:root}
    password: ${DB_PASS:root}
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    open-in-view: false
  mvc:
    static-path-pattern: /uploads/**
  sql:
    init:
      data-locations: classpath:data.sql
      mode: always
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  web:
    resources:
      static-locations: classpath:/static/uploads/

environment:
  urls:
    webapp: ${WEBAPP_BASE_URL}